language: node_js
node_js:
  - 14.17.4
cache: yarn

install:
  - yarn install
script:
  - node updatePwa.js

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages